### ISSUE TITLE
Is there a way to put clickButton in a 'simple mode'?

### ISSUE THREAD

**Issue by rayterrill** [pkourany/clickButton#9]
I love this module, but I've got a project where I don't need the full functionality - I really only need the ability to track whether/not a button was pressed, not discern between the various types of presses that might be done. Is there a config or set of settings I could apply to basically just get it to tell me whether/not a button was pressed, irrespective of length, etc?

**Comment by rayterrill** [comment]
It looks like this is possible by doing something like:
`
// Save click codes in LEDfunction, as click codes are reset at next Update()
  if(button1.clicks != 0) function = button1.clicks;
  
  if (function != 0) { #this appears to lump all the clicks types together
`

**Comment by pkourany** [comment]
@rayterrill, that is correct.  Can we close this issue then?

**Comment by rayterrill** [comment]
Closed issue as "working as designed".
